name: Publish snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
      - 'snapshot/*'
    paths-ignore:
      - '**.md'
      - '**.adoc'
      - '**/.gitignore'
      - './github/**'
      - '!./github/workflow/snapshot.yml'

defaults:
  run:
    working-directory: main

jobs:

  upload:
    name: Upload
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          path: main
          submodules: 'recursive'
      - name: Check out secp256k1-kmp
        uses: actions/checkout@v4
        with:
          repository: ImL1s/kotlin-secp256k1-kmp
          path: kotlin-secp256k1-kmp
          submodules: recursive
      - name: Install native build dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu binutils-aarch64-linux-gnu automake libtool
      - name: Setup Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-v2-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-v2-
      - name: Setup secp
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          cd $GITHUB_WORKSPACE/kotlin-secp256k1-kmp
          echo "skip.android=true" > local.properties
      - name: Check
        run: ./gradlew check --stacktrace --debug
      - name: Publish Linux to Maven Local
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: ./gradlew publishLinuxX64PublicationToMavenLocal
      - name: Publish MacOS to Maven Local
        if: matrix.os == 'macOS-latest'
        shell: bash
        run: |
          ./gradlew publishToMavenLocal
          echo "Listing Maven Local:"
          find ~/.m2/repository -name "secp256k1*"
      - name: Copy artifact files
        run: |
          mkdir -p maven-local/snapshot
          cp -r ~/.m2/repository/* maven-local/snapshot
      - name: Upload linux artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-linux
          path: |
            maven-local
            !maven-local/**/maven-metadata-local.xml
      - name: Upload macos artifacts
        if: matrix.os == 'macOS-latest'
        uses: actions/upload-artifact@v4
        with:
          name: snapshot-macos
          path: |
            maven-local
            !maven-local/**/maven-metadata-local.xml